export const paragraphs = [
    "Since then, SAF hosted the 2012 Kathmandu Arts Festival and the 2017 Kathmandu Triennale, and currently runs an education initiative training art managers, curators, and critics to build and support the growth of Nepali contemporary art practices.",
    "Over the years, SAF has partnered with many artists, art institutions and organizations to host exhibitions, workshops and art projects. The Foundation has been engaged in over 60 programs since its founding, including partnering with Artworks for Change (Oakland, California) to provide a platform for sex-trafficked and abused Nepali women to tell their stories, organizing two editions of the Kathmandu Triennale and starting its own arts education program through the Siddhartha Arts Foundation Education Initiative (SAFEI).",
    "Lorem, ipsum dolor sit amet consectetur adipisicing elit. Excepturi molestiae iste minima quia! Quod fuga labore similique harum iure non, obcaecati consectetur dicta necessitatibus, eum vitae, ex sequi autem rerum. Velit eum molestiae deserunt facilis quibusdam nobis voluptates tempora, labore reprehenderit deleniti aliquam iusto enim quos fuga eos repellat iure eaque tenetur qui incidunt saepe, harum, exercitationem quas sequi. Esse. Nesciunt, quaerat fugiat. Ab placeat, quia optio distinctio sint provident quasi, recusandae magnam minima aliquid facilis alias vel molestias quis voluptatibus corporis quidem necessitatibus repellendus porro hic enim. Culpa, pariatur! Quos soluta ad quasi et dolore quod commodi, hic libero maiores voluptas magnam corrupti. Iusto veritatis veniam nam vel necessitatibus qui quidem fuga, nihil illo, facilis cumque iure tempore odit. Sint iste mollitia sed saepe temporibus tempore aliquam officia molestiae, placeat recusandae vel cumque alias ullam maxime minima dicta earum culpa corrupti amet, quos quam illo? Praesentium debitis blanditiis ad."
  ];

  export const headline = [
  "After the first Kathmandu Arts Festival in 2009, the  Arts Foundation (AF) was founded in 2011 with the mission to promote and develop Nepali arts and culture."
];
