export {default as pattern} from '../assets/images/pattern.jpg';
export {default as HeroImg1} from '../assets/images/HeroImg1.jpg';
export {default as HeroImg2} from '../assets/images/HeroImg2.jpg';
export {default as HeroImg3} from '../assets/images/HeroImg3.jpg';
export {default as HeroImg4} from '../assets/images/HeroImg4.jpg';
export {default as background} from '../assets/images/background.png';
export {default as background1} from '../assets/images/background1.jpg';
export {default as background2} from '../assets/images/background2.jpg';
export {default as portrait} from '../assets/images/portrait.jpg';
export {default as GalleryImg1} from '../assets/images/GalleryImg1.jpg';
export {default as GalleryImg2} from '../assets/images/GalleryImg2.jpg';
export {default as GalleryImg3} from '../assets/images/GalleryImg3.jpg';
export {default as GalleryImg4} from '../assets/images/GalleryImg4.jpg';
export {default as GalleryImg5} from '../assets/images/GalleryImg5.jpg';
export {default as NewsImg1} from '../assets/images/NewsImg1.jpg';
export {default as NewsImg2} from '../assets/images/NewsImg2.jpg';
export {default as NewsImg3} from '../assets/images/NewsImg3.jpg';
export {default as NewsImg4} from '../assets/images/NewsImg4.jpg';
export {default as NewsImg5} from '../assets/images/NewsImg5.jpg';
export { default as head1 } from "../assets/images/head1.jpg";
export { default as head2 } from "../assets/images/head2.jpg";
export { default as head3 } from "../assets/images/head3.jpg";
export {default as head4} from "../assets/images/head4.jpg";
export {default as head5} from "../assets/images/head5.jpg";
export {default as head6} from "../assets/images/head6.jpg";